from .album1Serializer_test import *
from .albumSerializer_test import *
from .concertSerializer_test import *
from .musician2Serializer_test import *
from .musician1Serializer_test import *
from .musicianSerializer_test import *
from .songSerializer_test import *
from .musicianApi_test import *
from .albumApi_test import *
from .songApi_test import *
from .concertApi_test import *
from .musicianFetchInfluencer_test import *
from .musicianUpdateInfluencer_test import *
from .musicianFetchAll_test import *
from .musicianOnlyFetchApi_test import *
from .getAlbumsByStars_test import *
from .getAlbumSongs_test import *
